#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK

from __future__ import print_function, unicode_literals

import argcomplete
import argparse
import os
import requests

from clint.textui import colored, core, puts


def list_templates(args):
    templates = sorted(requests.get('http://gitignore.io/api/list').text.strip().split(','))
    for template in templates:
        print(template)


def generate_content(templates):
    parts = []

    for template in templates:
        content = requests.get('http://gitignore.io/api/%s' % template).text
        # skip comment header
        lines = content.splitlines()

        if not lines[0] == '# Generated by http://gitignore.io':
            raise IOError('Invalid content: \n%s' % content)

        content = '\n'.join(lines[2:])

        parts.append(content)

    return '\n\n'.join(parts) + '\n'


def print_templates(args):
    puts(generate_content(args.templates), newline=False)


def write_templates(args):
    puts("Writing... ", newline=False)

    gitignore = os.path.join(os.getcwd(), '.gitignore')

    if not args.overwrite and os.path.exists(gitignore):
        print(colored.yellow('exists'))
    else:
        try:
            with open(gitignore, 'w') as f:
                f.write(generate_content(args.templates))
                print(colored.green('done'))
        except Exception:
            print(colored.red('failed'))


parser = argparse.ArgumentParser(description='Generates a .gitignore file using http://gitignore.io')

commands = parser.add_subparsers(help='Available commands')

list_command = commands.add_parser('list', help='List all available templates.')
list_command.set_defaults(action=list_templates)

write_command = commands.add_parser('write', help='Writes the specified templates to the .gitignore file.')
write_command.set_defaults(action=write_templates)
write_command.add_argument('--overwrite', dest='overwrite', action='store_true', default=False)
write_command.add_argument('templates', nargs='+', metavar='template',
                           help='Selected templates used to generate the .gitignore file.')

print_command = commands.add_parser('print', help='Print the ignore patterns of the specified templates.')
print_command.set_defaults(action=print_templates)
print_command.add_argument('templates', nargs='+', metavar='template',
                           help='Selected templates used to generate the .gitignore patterns.')

argcomplete.autocomplete(parser)
args = parser.parse_args()

try:
    args.action(args)
except KeyboardInterrupt:
    pass
except Exception, e:
    puts(str(e), stream=core.STDERR)
